version: 2
enable-beta-ecosystems: true # Julia ecosystem
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "crate-ci/typos"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
  - package-ecosystem: "julia"
    directories:
      - "/"
      - "/test"
    schedule:
      interval: "daily"
    groups:
      all-julia-packages:
        patterns:
          - "*"
